version: '3.7'
services:
  postgres:
    image: postgres:14
    container_name: foxia-auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foxia_auth
    ports:
      - '5432:5432'
    volumes:
      - foxia-auth-postgres-data:/var/lib/postgresql/data
    networks:
      - foxia-auth-network

  redis:
    image: redis:7
    container_name: foxia-auth-redis
    ports:
      - '6379:6379'
    volumes:
      - foxia-auth-redis-data:/data
    networks:
      - foxia-auth-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: foxia-auth-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - foxia-auth-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - foxia-auth-network

networks:
  monitoring:
    driver: bridge
  foxia-auth-network:
    driver: bridge

volumes:
  foxia-auth-postgres-data:
    driver: local
  foxia-auth-redis-data:
    driver: local
  foxia-auth-rabbitmq-data:
    driver: local
 
